### ISSUE TITLE
Suggestion: use NOOP from utilities

### ISSUE THREAD

**Issue by ChenReuven** [mondaycom/vibe#1260]
Hey :)

**Issue: Code Reusability** 
- I note that you have several places that re-create this functionality:
```const NOOP = () => {};```

**Solution:**
- You have already this function in a utility:
https://github.com/mondaycom/monday-ui-react-core/blob/3f9ab8b47c424748a54a0488d54bb642e84c40f3/src/utils/function-utils.ts#L48

Just import it and use it :)

**Comment by shlomitc** [comment]
Hey Chen and thanks for the suggestion!
We'll be happy to receive this change as a contribution.
Also - it might be a good idea to add a lint rule to prevent regressions.

**Comment by ChenReuven** [comment]
> 

@shlomitc which lint rule enforces this functionality? (i am not familiar)

**Comment by shlomitc** [comment]
There might be one but I didn’t search for it, however it should be quite simple to write one

**Comment by ChenReuven** [comment]
> There might be one but I didn’t search for it, however it should be quite simple to write one

a linter that scans all your repo finds usages, and understands if there is some "Util" function that does the same logic as you expect...

i think it not a simple one :)

**Comment by shlomitc** [comment]
a simple lint rule that checks there are no empty function declaration

**Comment by ChenReuven** [comment]
> a simple lint rule that checks there are no empty function declaration

okie, 

i meant something more generic

**Comment by talkor** [comment]
@ChenReuven thanks for the suggestion, we will keep this in mind and if there's anything specifically we'd be happy if you'd want to contribute and open a PR :)
