### ISSUE TITLE
Dropdown with multiselect ignores custom valueRenderer

### ISSUE THREAD

**Issue by aprokopczyk** [mondaycom/vibe#1386]
Hello,
I need to use Dropdown with the custom option Renderer in my app. I've noticed that the custom renderer is ignored when the Dropdown is in multi-select mode. The best way to reproduce the issue would be to use https://style.monday.com/?path=/docs/inputs-dropdown--dropdown-with-lables and add "multi multiline" attributes.

Do you have any plans to fix it?

Kind regards,
Andrzej

**Comment by talkor** [comment]
Hey @aprokopczyk ! Thanks for submitting this issue. Could you please attach a code snippet reproducing the issue? Also please mention the vibe version you use. Thank you
