### ISSUE TITLE
TS-migration: Dropdown

### ISSUE THREAD

**Issue by SergeyRoyt** [mondaycom/vibe#1622]
[Monday ticket](https://monday.monday.com/boards/3532714909/pulses/3829675448)

Scope of this task is to convert only the main Dropdown file - `Dropdown.jsx` to typescript
Please, check out the [Typescript migration guide](https://github.com/mondaycom/monday-ui-react-core/blob/master/TYPESCRIPT_MIGRATION.md)

**Comment by Petsamuel** [comment]
Hi @SergeyRoyt im interested in this issue

**Comment by ayeolakenny** [comment]
I’m interested in this issue

**Comment by SergeyRoyt** [comment]
Assigned to you @ayeolakenny! Good luck with that

**Comment by ayeolakenny** [comment]
Thanks

**Comment by Aady7** [comment]
Would like to work on this issue is it still open?

**Comment by ansumanswain** [comment]
yes

**Comment by Aady7** [comment]
@SergeyRoyt assign me the issue

**Comment by ansumanswain** [comment]
Done.

**Comment by SergeyRoyt** [comment]
Hey @ansumanswain !
Don't see your pull request. Please, reference the issue there

**Comment by Aady7** [comment]
Thanks will work on it.

**Comment by SergeyRoyt** [comment]
Hey @ansumanswain! You need to fork our repository

![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/90d3f895-e2a7-4168-a65e-75f9054b38a6)

For further instruction u'll need to follow this guide https://github.com/mondaycom/monday-ui-react-core/blob/master/CONTRIBUTING.md

If you are still interested I think it's better for you to start with more simple issues - this one might be a bit hard

**Comment by Aady7** [comment]
@SergeyRoyt  In this issue I need to change the jsx file to transcript, I guess I will be able to fix it, feel free to assign me some good first issues if they arise.
_thanks_

**Comment by SergeyRoyt** [comment]
Hey @Aady7!
 If you've managed to make any progress with the issue, it's better to submit it now, cause Hacktoberfest if coming to the end in a few days 🙏

**Comment by shaharzil** [comment]
Still open to contributions if anyone is interested :)

**Comment by Mila2999** [comment]
Hi @shaharzil @SergeyRoyt , I would like to work on this issue

**Comment by talkor** [comment]
> Hi @shaharzil @SergeyRoyt , I would like to work on this issue

Thanks @Mila2999 that would be great!
