### ISSUE TITLE
[Bug]: Dropdown with multiselect and size small has several issues

### ISSUE THREAD

**Issue by pjastrzebski-appfire** [mondaycom/vibe#2022]
### Vibe version

2.96.0

### Describe the bug

<img width="1263" alt="image" src="https://github.com/mondaycom/monday-ui-react-core/assets/158473312/274cc6ab-753d-49da-b514-afa82bc649d6">

As you can see on above screenshot, if the dropdown slot is of size `small` there are several issues:
- the selected options are not displayed correctly
- the counter is displayed even though all the selected options are  displayed and it shows incorrect information
- if you open the counter dialog you will see all the selected elements

### Expected behavior

Dropdown with size `small` should work in same way as with other sizes.

### Steps to reproduce

1. Select option in dropdown
2. Notice issue

### Reproduction example link

https://vibe-bug-report-sn8c9u.stackblitz.io/

**Comment by kenrick** [comment]
Looks like there is a migration underway for Dropdown. https://github.com/mondaycom/monday-ui-react-core/pull/1976. This could be a good place to fix as well.

**Comment by talkor** [comment]
Fixed in #2174 , release in `v2.113.1`
