### ISSUE TITLE
[Bug]: DatePicker | no null protection for onPickDate callback

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2045]
Using the DatePicker component without the `onPickDate` prop provided results in a console error.
Suggested solution: add null protection for the `onPickDate` prop.

<img width="480" alt="Screenshot 2024-04-03 at 13 53 44" src="https://github.com/mondaycom/monday-ui-react-core/assets/18269880/52dafbc0-2485-4390-afa8-2fa8ec98dc86">

monday ticket: https://monday.monday.com/boards/3532714909/pulses/6381326498

**Comment by YossiSaadi** [comment]
resolved at #2102
