### ISSUE TITLE
[Bug]: Dropdown font is broken

### ISSUE THREAD

**Issue by ramarm** [mondaycom/vibe#2182]
### Vibe version

2.113

### Describe the bug

When using the Dropdown component the don't is the default browser font. But when I put it in a model it actually works fine.

### Expected behavior

The font should be the vibe font

### Steps to reproduce

Here is a video showing how to reproduce - https://www.loom.com/share/180cd2b8372c469cb69630b2c91d28ba?sid=7e48cf40-5506-4900-85d2-d06ddf8dbe24
Here is a link for a public repo - https://github.com/ramarm/vibe-bug

### Reproduction example link

https://www.loom.com/share/180cd2b8372c469cb69630b2c91d28ba?sid=7e48cf40-5506-4900-85d2-d06ddf8dbe24

**Comment by malavshah9** [comment]
@talkor  I have worked on this and here is the PR, please assign this to me and review this once you get time: https://github.com/mondaycom/vibe/pull/2551

**Comment by malavshah9** [comment]
@talkor Could you please also add the label `hacktoberfest-accepted`?
Thanks!
