### ISSUE TITLE
[Docs]: convert Menu.stories.js to TS 

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2206]
## Description

- Change `Menu.stories.js` file extension to `.tsx`
- Fix TS issues if exists (avoid using `any`)

Example similar file for reference: `packages/core/src/components/Search/__stories__/Search.stories.tsx`

Thanks!

**Comment by itaim18** [comment]
Hey, I'll be happy to be assigned on this issue :)

**Comment by itaim18** [comment]
@talkor close this ;)

**Comment by talkor** [comment]
Resolved in https://github.com/mondaycom/vibe/pull/2260, thanks @itaim18 :)
