### ISSUE TITLE
[Docs]: convert AlertBanner.stories.js to TS

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2207]
## Description

- Change `AlertBanner.stories.js` file extension to `.tsx`
- Fix TS issues if exists (avoid using `any`)

Example similar file for reference: `packages/core/src/components/Search/__stories__/Search.stories.tsx`

Thanks!

**Comment by sahil-172002** [comment]
can i resolve this?

**Comment by talkor** [comment]
Sure @sahil-172002! That would be great :) Thanks!

**Comment by Hossein-Mirazimi** [comment]
@sahil-172002 

are you working on it?

**Comment by GurneeshBudhiraja** [comment]
Hi there! 🙂
This is my first contribution to the project. I hope I've followed all the guidelines correctly. If there's anything I should fix or improve in the PR, please let me know. I'm eager to learn and contribute more to this wonderful open-source community.

Thank you!
