### ISSUE TITLE
[Bug]: Warning Toast Type renders nothing

### ISSUE THREAD

**Issue by number1hustler** [mondaycom/vibe#2401]
### Vibe version

    "monday-ui-react-core": "^1.134.1"

### Describe the bug

The warning toast is blank screenshots: 
![Screenshot 2024-08-28 at 1 17 20 PM](https://github.com/user-attachments/assets/8418ffe4-748a-4d88-8c51-87de1f198315)
![Screenshot 2024-08-28 at 1 17 14 PM](https://github.com/user-attachments/assets/40622b1a-7f6c-457d-ba88-39f72935473e)

The negative works: 
![Screenshot 2024-08-28 at 1 17 35 PM](https://github.com/user-attachments/assets/7267113c-e864-499d-aef1-84f45c796946)
![Screenshot 2024-08-28 at 1 20 45 PM](https://github.com/user-attachments/assets/1f1d1714-5967-4cc0-a11f-664458fb3ae9)

### Expected behavior

All the types should work

### Steps to reproduce

Create a toast and use the negative and warning types

**Comment by talkor** [comment]
Hey @number1hustler! Thank you for reporting this issue!
This feature (Toast warning variant) was introduced in [v2.49.0](https://github.com/mondaycom/vibe/blob/master/packages/core/CHANGELOG.md#new-features-42). I see you're using v1, please follow the [migration guide to v2](https://github.com/mondaycom/vibe/blob/master/packages/core/VERSION_2_MIGRATION.md) and check back if this feature works as expected. Thanks!
