### ISSUE TITLE
[Bug]: BreadcrumbItem does not properly represent applied theming.

### ISSUE THREAD

**Issue by mKistnerDecadis** [mondaycom/vibe#2441]
### Vibe version

2.134.1

### Describe the bug

If a  BreadcrumbItem of the Vibe design system is truncated the connected tooltip to show the missing text that is overflown does not properly represent the theming.

On most of the other components within the design system you allow to pass down tooltipProps to fix that which feels missing here.

### Expected behavior

I would exspect to control a tooltip wrapper properly from the outside when used within a component with the tooltipProps.

For example following the pattern used on {EditableText} from "monday-ui-react-core"
tooltipProps={{className: `${theme}-app-theme`, arrowClassName: `${theme}-app-theme`}}

### Steps to reproduce

Add breadcumb comp don't give enough space make to make the tooltip render. 
Tooltip is not properly using the applied theming

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 1.26 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.59
    Safari: 17.4.1
  npmPackages:
    monday-ui-react-core: 2.134.1 => 2.134.1 
    react: ^18.2.0 => 18.3.1
```

### Additional context, Screenshots

![Xnip2024-09-25_08-31-46](https://github.com/user-attachments/assets/d1154b0b-3b7d-4241-89e9-d98b27b2addc)
![Xnip2024-09-25_08-31-54](https://github.com/user-attachments/assets/d6445dd2-df8d-436d-b48e-00d0b50fda2c)

**Comment by YossiSaadi** [comment]
Hey @mKistnerDecadis!
I'm seeing this on our Storybook:
![image](https://github.com/user-attachments/assets/26083265-4f5f-4d15-b572-5d5819149313)

Any chance you can create a reproducible example on some codesandbox or in our [Playground](https://vibe.monday.com/?path=/story/playground--playground&globals=theme:Dark)?

**Comment by mKistnerDecadis** [comment]
Sorry i think its fine on your end (If you use the themeProvider which does not require any classname adjustments on comp level to recognize with theme is used)

So i can fix it by just using the themeprovider instead of manualy applying classes

 https://vibe.monday.com/?path=/story/theming-themeprovider-alpha--monday-sdk-integration. 

Question the comp is still declared as alpha do you think its fine to be used in prod?

**Comment by YossiSaadi** [comment]
@mKistnerDecadis You should basically get the updated vars values from monday, through the `body`
I don't believe you need to use the `ThemeProvider` for that use case, but will make sure with the team

Can you please share with me, when you're on dark theme:
- What's the theme value on the `body`?
- What is the value of `var(--inverted-color-background)` when you switch between themes?

**Comment by mKistnerDecadis** [comment]
Just to share my understanding how things work you may correct me here please:

The tokens are currently pushed to the core products css (monday.com product body tag).

We as app vendors operate inside an iframe 
(so the only body we can access is the one inside our apps (  which for me does not come with any theming information).

The information which specific tokens if dark or white or whatever are derived from the output of monday sdk:

`export default function useMondayTheme() {
	const [theme, setTheme] = useState<string>('');

	useEffect(() => {
		monday.listen('context', res => {
			setTheme((res.data as any).theme);
		});
	}, []);

	return theme;
}`

within the app without provider you than had to supply theming information to each comp somehow like this:

` classNames={{container: `${theme}-app-theme`}} for example for a Modal comp to know in which theming state it is.`

We as a app vendor don't have access to the core products tokens as we are limited due to security concerns to access any element above the parent this includes css.

The monday UI kit comps are supplying the tokens to be used in the app themself at least AttentionBox does see screenshot of node modules here:

![Xnip2024-09-26_11-23-10](https://github.com/user-attachments/assets/2dd6f369-f050-42ed-9946-48d462bbf735)



To in summary answer your questions:

var(--inverted-color-background)   = #ffffff

no theme attribute tag on app body 
on product level its applied as class "dark-app-theme" 


But if i get you right everything should work if we just apply things on root level of the react app which means do the changes on index.html within a script and add the correct theme as class to the body?

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Batch Hero for Monday</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./src/main.tsx"></script>
  </body>
</html>
`

Thanks for the response and your time! much appreciated.

**Comment by mKistnerDecadis** [comment]
But for me its fine to close this issue :) The use of themeProvider from a developer point of view is just nice and your competitors also doing this see here: https://atlassian.design/components/app-provider/examples

**Comment by YossiSaadi** [comment]
@mKistnerDecadis
I got what you mean, I missed the iframe issue
You're totally right in that case!
Each of the solutions should work, I agree that using the ThemeProvider is a more elegant solution

We have started discussing the future of ThemeProvider lately.
And though it is marked as Alpha, and therefore experimental and eligible for changes, we do not tend to make breaking changes.
We're planning on releasing Vibe 3.0 soon, and might call ThemeProvider as stable there

Closing the issue for now, please feel free to contact us again in case something comes up :)
