### ISSUE TITLE
[Bug]: VITE not including css vars at :root in build (they exist in dev not prod)

### ISSUE THREAD

**Issue by ohabash** [mondaycom/vibe#2456]
### Vibe version

`"monday-ui-react-core": "^2.134.1",`

### Describe the bug

_VITE React Dev server_ =>
In my VITE react app when i start the app in dev mode all the styles exist and css vars

_After Build_ =>
after build some of the styles exist and the css vars on :root do not exist and everything looks a little incomplete.

### Expected behavior

Was expecting that the css variables on :root would be available in the built app as it was in the dev app. 

### Steps to reproduce

1. Create React app with VITE
2. use component from `monday-ui-react-core`. (I used `EditableHeading`)
3. start in dev (note all looks good) 
4. build
5. start built app and not that there are missing css vars

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 129.0.6668.72
    Safari: 17.1.2
  npmPackages:
    monday-ui-react-core: ^2.134.1 => 2.134.1 
    react: 18.3.1 => 18.3.1

**Comment by talkor** [comment]
Thanks for opening this issue @ohabash !
Can you please clarify if you imported the tokens as mentioned [here](https://github.com/mondaycom/vibe/blob/master/packages/core/README.md#usage)?

**Comment by ohabash** [comment]
I didnt. My bad! great library btw

for the record - dont for get to put this at the root of you react app `import 'monday-ui-react-core/tokens';`

**Comment by talkor** [comment]
Cool! Thanks! We'll make sure it's clearer in the README
