### ISSUE TITLE
docs: add Related Component section to VirtualizedList and VirtualizedGrid docs

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2470]
In every component page there's a Related Component section, for example:
<img width="1210" alt="Screenshot 2024-10-09 at 18 18 50" src="https://github.com/user-attachments/assets/ebac2a81-3c4f-481a-8037-21b9f72d726a">

The `VirtualizedList` and `VirtualizedGrid` pages are missing these section.

Need to add the following:
- For  `VirtualizedList`: `List`, `VirtualizedGrid`, `Table`
- For `VirtualizedGrid`: `Table`, `VirtualizedList`, `MenuGridItem`

## Related files
`packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.mdx`
`packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.mdx`

## Example that uses related components section:
`packages/core/src/components/Accordion/Accordion/__stories__/Accordion.mdx:105`

---
[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/5658462914)

**Comment by PrzemyslawPolrolniczak** [comment]
I'll take it

**Comment by PrzemyslawPolrolniczak** [comment]
#2479
