### ISSUE TITLE
docs: convert useHover stories file to TS

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2472]
Convert the `useHover` stories file to TypeScript:
- Change extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useHover/__stories__/useHover.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7586908181)

**Comment by PrzemyslawPolrolniczak** [comment]
I can take it

**Comment by PrzemyslawPolrolniczak** [comment]
#2478

**Comment by talkor** [comment]
Resolved in #2478
