### ISSUE TITLE
docs: convert useListenFocusTriggers stories file to TS

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2474]
Convert the `useListenFocusTriggers` stories file to TypeScript:
- Change the file extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7601008784)

**Comment by LoayTarek5** [comment]
Hi @talkor I am happy to contribute to this issue and solve it, could i

**Comment by TheSoumenMondal** [comment]
**Assign this to me . I would like to work on this issue**

**Comment by talkor** [comment]
Thanks both! Assigned to @LoayTarek5 as they were first, @TheSoumenMondal feel free to take other issues if you'd like :)
