### ISSUE TITLE
docs: convert useDebounceEvent stories file to TS

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2475]
Convert the `useDebounceEvent` stories file to TypeScript:
- Change the file extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useDebounceEvent/__stories__/useDebounceEvent.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7601044163)

**Comment by ahammadabdullah** [comment]
Hey, I can do this assign me please.

**Comment by ayush1009208** [comment]
Hey @talkor i have previous expeirience with ts...CAn you assign this to me?

**Comment by talkor** [comment]
Thanks both! Assigned to @ahammadabdullah  as they were first, @ayush1009208  feel free to take other issues if you'd like :)

**Comment by ahammadabdullah** [comment]
i already solved the issue. I'll create this pr once my last pr get approved. @talkor

**Comment by talkor** [comment]
> i already solved the issue. I'll create this pr once my last pr get approved. @talkor

Please create a PR as those issues are unrelated, thanks!
