### ISSUE TITLE
docs: convert useClickableProps stories file to TS

### ISSUE THREAD

**Issue by talkor** [mondaycom/vibe#2476]
Convert the `useClickableProps` stories file to TypeScript:
- Change the file extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useClickableProps/__stories__/useClickableProps.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7601091903)

**Comment by ahammadabdullah** [comment]
hey i want to work on this issue. Assign please.

**Comment by namansharma3007** [comment]
> Convert the `useClickableProps` stories file to TypeScript:
> 
> * Change the file extension to `stories.tsx`
> * Resolve type issues (if there are), avoid using `any` and prefer existing types
> 
> ## Related files
> `packages/core/src/hooks/useClickableProps/__stories__/useClickableProps.stories.js`
> 
> [Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7601091903)

I can handle this issue. I have been working with typeScript for more than 2 years.

**Comment by talkor** [comment]
Thanks both! Assigned to @ahammadabdullah as they were first, @namansharma3007  feel free to take other issues if you'd like :)

**Comment by ahammadabdullah** [comment]
@talkor im getting test error without any changes 
![image](https://github.com/user-attachments/assets/609fb64d-488d-43b8-a3de-2b99012d8cf8)

**Comment by ahammadabdullah** [comment]
@talkor bro any update ?

**Comment by talkor** [comment]
Closing for now as there should be a fix to useClickableProps's ref's type
