### ISSUE TITLE
fix: <Combobox /> onClick gets triggered also on disabled options

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2481]
When disabling an option in the `Combobox`, the option visually appears disabled, but it continues to receive click events. This behavior is unexpected, as disabled options should not trigger click events.

## Related files
`packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx`

---
[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/6643403859)

**Comment by masabinhok** [comment]
I can fix this @rivka-ungar
