### ISSUE TITLE
docs: add options to dropdown in the catalog

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2482]
In the [Catalog](https://vibe.monday.com/?path=/docs/catalog--docs) there are interactive examples of components.

The `Dropdown` has no options. See screenshot:

<img width="337" alt="Screenshot 2024-10-09 at 22 32 08" src="https://github.com/user-attachments/assets/891404d2-4835-4a93-830a-da7ab303b9aa">

Need to add options: Option 1, option 2, Option 3

## Related files
`packages/core/src/storybook/components/related-components/descriptions/dropdown-description.jsx`

---
[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/5506746664)

**Comment by masabinhok** [comment]
I would like to work on this @rivka-ungar

**Comment by masabinhok** [comment]
@GurneeshBudhiraja, It's important to follow the open-source rules regarding task assignments.
Typically, contributors should focus on tasks they are assigned to, to avoid duplication of effort.

**Comment by GurneeshBudhiraja** [comment]
@masabinhok Thanks for the comment. Since no PR had been raised by the assignee (you), I took the initiative to work on it and submit a PR. It is up to the maintainers to decide which PR they want to merge. Thanks!

**Comment by GurneeshBudhiraja** [comment]
> @GurneeshBudhiraja, It's important to follow the open-source rules regarding task assignments. Typically, contributors should focus on tasks they are assigned to, to avoid duplication of effort.


@masabinhok Thanks for the comment. Since no PR had been raised by the assignee (you), I took the initiative to work on it and submit a PR. It is up to the maintainers to decide which PR they want to merge. Thanks!
