### ISSUE TITLE
docs: <AttentionBox /> change container size in story

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2483]
[AttentionBox with link](https://vibe.monday.com/?path=/docs/feedback-attentionbox--attention-box-with-link):
Change container size to 350px
![image](https://github.com/user-attachments/assets/f2f7f873-3846-4641-bede-a3198ac093e4)

[Dismissible AttentionBox](https://style.monday.com/?path=/docs/feedback-attentionbox--dismissable):
Change container size to 274px
![image](https://github.com/user-attachments/assets/8f587768-ae4f-4e83-a705-c85bbfccc346)

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/views/80492480/pulses/5618073848)

**Comment by NechamaSopher** [comment]
@rivka-ungar Hi, Can you please assign this to me?
