### ISSUE TITLE
Convert the "Spacing" docs page to not use `Story` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2498]
Convert the "Spacing" page to use Storybook's latest convention.
Storybook has deprecated the usage of `Story` component in mdx files.

Instead of:
```typescript
<Canvas>
  <Story name="Spacing sizes">
    <SpacingSizes />
  </Story>
</Canvas>
```

It should be something like:
```typescript
<Canvas of={SpacingStories.Sizes}>
```

**In our case, we also don't want to show the code for this story, so more specifically:**
```typescript
<Canvas of={SpacingStories.Sizes} sourceState="none">
```

This requires:
- Create a new file called `spacing.stories.tsx` in the same folder where the `spacing.stories.mdx` file is, in the format of [CSF](https://storybook.js.org/docs/api/csf).
	- It's content should be something like:
```typescript
const meta: Meta = {
  title: "Foundations/Spacing"
};
export default meta;

type Story = StoryObj;

export const Sizes: Story = {
  render: SpacingSizes
};
```

- Change the file name of `spacing.stories.mdx` to `Spacing.mdx`
	- Its content should change according to the above `<Canvas />` example, 
	- `Meta` should, instead of having a "title" attr, have a "of" attr, with the value of `SpacingStories`. 
	(which is imported according to our convention as `import * as SpacingStories from "./spacing.stories.tsx"`)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/6360059603

**Comment by vaibhavj2111** [comment]
I will work on this issue. Please assign this to me.

**Comment by YossiSaadi** [comment]
@vaibhavj2111 go for it :)
