### ISSUE TITLE
Convert the "Colors" docs page to not use `Story` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2499]
Convert the "Colors" page to use Storybook's latest convention.
Storybook has deprecated the usage of `Story` component in mdx files.

There are 5 stories that should be migrated:
- Semantic colors
- Background colors
- Text colors
- Border colors
- Content colors

Example:
Instead of:
```typescript
<Canvas>
  <Story name="Semantic Colors">
    <SemanticColors />
  </Story>
</Canvas>
```

It should be something like:
```typescript
<Canvas of={ColorsStories.Semantic}>
```

**In our case, we also don't want to show the code for this story, so more specifically:**
```typescript
<Canvas of={ColorsStories.Semantic} sourceState="none">
```

This requires:
- Create a new file called `colors.stories.tsx` in the same folder where the `colors.stories.mdx` file is, in the format of [CSF](https://storybook.js.org/docs/api/csf).
	- It's content should be something like:
```typescript
const meta: Meta = {
  title: "Foundations/Colors"
};
export default meta;

type Story = StoryObj;

// this is one example, it should have a Story object for each of the above stated stories
export const Semantic: Story = {
  render: SemanticColors
};
```

- Change the file name of `colors.stories.mdx` to `Colors.mdx`
	- Its content should change according to the above `<Canvas />` example, 
	- `Meta` should, instead of having a "title" attr, have a "of" attr, with the value of `ColorsStories`. 
	(which is imported according to our convention as `import * as ColorsStories from "./colors.stories.tsx"`)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/6360059299

**Comment by theDevSoham** [comment]
Good day @YossiSaadi can I work on this issue if it is available?

**Comment by YossiSaadi** [comment]
@theDevSoham go for it :)

**Comment by YossiSaadi** [comment]
Hey @theDevSoham, please update if you still planning on working on that one

**Comment by theDevSoham** [comment]
@YossiSaadi yes I'm working on this issue

**Comment by theDevSoham** [comment]
@YossiSaadi please check
