### ISSUE TITLE
Block text selection on monday-ui-react-core disabled button

### ISSUE THREAD

**Issue by hadasfa** [mondaycom/vibe#250]
https://user-images.githubusercontent.com/72390374/136784936-6f5566dd-cf7a-40a6-8536-e472a89fe49b.mov

**Comment by pedaars** [comment]
I have submitted a pr for this issue.

During my initial testing, I found that you could also select the text on an active button if you mouse down just before the button element and drag over it.
So I have added the CSS fix to the whole button element.
