### ISSUE TITLE
Convert a deprecated `Story` usage in Modal's docs page to use `Canvas`

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2500]
Storybook has deprecated the usage of `Story` component in mdx files.
In Modal's story, we have:
```typescript
### Sizes

<Canvas>
  <Story of={ModalStories.WidthVariantsNormal} />
  <Story of={ModalStories.WidthVariantsFull} />
  <Story of={ModalStories.WidthVariantsCustom} />
</Canvas>
```

We need it to be instead:
```typescript
### Sizes

<Canvas of={ModalStories.Sizes} />
```

See `Button`'s story for ["Sizes"](https://github.com/mondaycom/vibe/blob/master/packages/core/src/components/Button/__stories__/Button.mdx#sizes)
And its appropriate [story source](https://github.com/mondaycom/vibe/blob/master/packages/core/src/components/Button/__stories__/Button.stories.tsx#L53)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/5661351160

**Comment by GurneeshBudhiraja** [comment]
Hey! I am working on it. Could you please assign this to me?

**Comment by YossiSaadi** [comment]
@GurneeshBudhiraja go for it :)

**Comment by YossiSaadi** [comment]
@GurneeshBudhiraja I see you removed your comment, do you still want to take this one?
if so, please comment here

**Comment by GurneeshBudhiraja** [comment]
Sure! Looks like the comment was deleted by mistake.

**Comment by GurneeshBudhiraja** [comment]
I will raise a PR for this soon :)

**Comment by YossiSaadi** [comment]
This one still open

**Comment by aarifkhan7** [comment]
Hey @YossiSaadi,

I'm a beginner interested in contributing to open source, and this issue seems like a good starting point for me. Could you please assign it to me?

Thanks!

**Comment by YossiSaadi** [comment]
@aarifkhan7 of course :)
Pay attention to what I've wrote in the previous, closed, PR.

You'll need to mimic the behavior that is in Button's "Sizes" story, just for this component.

So to render everything that's under the Canvas of "Sizes" in the "mdx" file, under a single story, at the ".stories.tsx" file of the component. 

If any further clarification is needed let me know :)

Good luck!
