### ISSUE TITLE
Remove deprecated colors names from "Divider" catalog component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2501]
We have the "Divider" catalog component (aka RelatedComponent).
`packages/core/src/storybook/components/related-components/descriptions/divider.jsx`.

We need to remove the colors names suffix for both list items, as those are deprecated colors.

![image](https://github.com/user-attachments/assets/3b4efc4b-8378-4489-91dd-bad1cb6cecda)
-->
![image](https://github.com/user-attachments/assets/fe09d66f-333c-49ba-9d50-f28e565d064f)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/5506743822

**Comment by shawaiz-khan** [comment]
Can I do this?

**Comment by YossiSaadi** [comment]
@shawaiz-khan go for it :)

**Comment by shawaiz-khan** [comment]
Sure, Assign it to me

**Comment by YossiSaadi** [comment]
@shawaiz-khan I see that @GurneeshBudhiraja already started working on it
@GurneeshBudhiraja Thanks for the contribution, really appreciate your help! Can you please give a heads up in each of the issue pages your working on? so people would know not work on it simultaneously and to not create double PRs?

I want to give @shawaiz-khan the chance to contribute it, as he wrote here he wants to work on it before your PR was merged

**Comment by GurneeshBudhiraja** [comment]
Not a problem @YossiSaadi. I will take care of this. 
Thanks!

**Comment by shawaiz-khan** [comment]
Yes, as per rule, you have to tell the owner of the issue that you are working on it and you must be assigned the issue in order to submit a PR, isn't it?

**Comment by YossiSaadi** [comment]
yes, indeed
since we have many very straightforwards issues, we want them to be a "first-come first-served", but we would appreciate mentioning in issues if you're planning to work on it soon
we also have a lot requests to contribute so we want the accelerate the process, both for the contributor and for Vibe

**Comment by shawaiz-khan** [comment]
Yeah sure

**Comment by YossiSaadi** [comment]
@GurneeshBudhiraja I've marked your PR with "hacktoberfest-accepted", so you'll get your point for this issue as well

@shawaiz-khan feel free to create a PR :)

**Comment by GurneeshBudhiraja** [comment]
@YossiSaadi thanks a million

**Comment by shawaiz-khan** [comment]
> @GurneeshBudhiraja I've marked your PR with "hacktoberfest-accepted", so you'll get your point for this issue as well
> 
> @shawaiz-khan feel free to create a PR :)

Yeah, created a PR

**Comment by shawaiz-khan** [comment]
@YossiSaadi Can you mark my PR also for hacktoberfest-accepted?

**Comment by YossiSaadi** [comment]
@shawaiz-khan once a PR is merged or approved it is considered also as accepted
can you check if that was counted for you?

**Comment by shawaiz-khan** [comment]
> @shawaiz-khan once a PR is merged or approved it is considered also as accepted
> can you check if that was counted for you?
Checking

**Comment by shawaiz-khan** [comment]
Now it's approved
