### ISSUE TITLE
Change `VirtualizedList` catalog component to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2504]
In the file of:
`packages/core/src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx`
which can be seen on our [Catalog](https://vibe.monday.com/?path=/docs/catalog--docs) page, we do not currently use Vibe's `Text` component, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

We need to change the wrapper `div` to be `Text` instead.
```typescript
<div
  className={styles.virtualizedListItem}
  style={{
    backgroundColor,
    height: item.height
  }}
>
  {item.value}
</div>
```
--> Something like
```typescript
<Text
  className={styles.virtualizedListItem}
  color={Text.colors.FIXED_DARK}
  style={{
    backgroundColor,
    height: item.height
  }}
>
  {item.value}
</Text>
```

Notice the `FIXED_DARK` color addition as well - we need it so it would be shown correct on all themes.

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by GurneeshBudhiraja** [comment]
working on it
