### ISSUE TITLE
Change `VirtualizedGrid` catalog component to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2505]
In the file of:
`packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.helpers.js`
which can be seen on our [Catalog](https://vibe.monday.com/?path=/docs/catalog--docs) page, we do not currently use Vibe's `Text` component, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

We need to change the wrapper `div` to be `Text` instead.
```typescript
<div
  style={{
    backgroundColor,
    height: item.height,
    width: item.width,
    display: "flex",
    alignItems: "center",
    justifyContent: "center"
  }}
>
  {item.value}
</div>
```
--> Something like
```typescript
<Text
  color={Text.colors.FIXED_DARK}
  style={{
    backgroundColor,
    height: item.height,
    width: item.width,
    display: "flex",
    alignItems: "center",
    justifyContent: "center"
  }}
>
  {item.value}
</Text>
```

Notice the `FIXED_DARK` color addition as well - we need it so it would be shown correct on all themes.

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by GurneeshBudhiraja** [comment]
I am working on this too.
Thanks !!

**Comment by shawaiz-khan** [comment]
> I am working on this too. Thanks !!

Haha I came here for the same thing :) Good Luck btw
