### ISSUE TITLE
Change `Box` catalog component to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2506]
In the file of:
`packages/core/src/storybook/components/related-components/descriptions/box-description.jsx`
which can be seen on our [Catalog](https://vibe.monday.com/?path=/docs/catalog--docs) page, we do not currently use Vibe's `Text` component, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

```typescript
<div
  style={{
    width: "80%",
    textAlign: "center"
  }}
>
  <Box border={Box.borders.DEFAULT} rounded={Box.roundeds.MEDIUM}>
    Box
  </Box>
</div>
```
--> Something like
```typescript
<div
  style={{
    width: "80%"
  }}
>
  <Box border={Box.borders.DEFAULT} rounded={Box.roundeds.MEDIUM}>
    <Text align={Text.align.CENTER}>Box</Text>
  </Box>
</div>
```

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by caronvincent** [comment]
I would like to work on this issue if it's still up for grabs.

**Comment by YossiSaadi** [comment]
@caronvincent it's yours, good luck 😊
