### ISSUE TITLE
Change `DialogContentContainer` catalog component to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2508]
In the file of:
`packages/core/src/storybook/components/related-components/descriptions/dialog-content-container.jsx`
which can be seen on our [Catalog](https://vibe.monday.com/?path=/docs/catalog--docs) page, we do not currently use Vibe's `Text` component, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

```typescript
<DialogContentContainer>
  <p>A content section within an elevated dialog content container</p>
</DialogContentContainer>
```
--> Something like
```typescript
<DialogContentContainer>
  <Text ellipsis={false}>A content section within an elevated dialog content container</Text>
</DialogContentContainer>
```

Notice the `ellipsis` as `false` as well.

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by noyshlomo** [comment]
Hi, Can you please assign this to me?

**Comment by YossiSaadi** [comment]
@noyshlomo go for it :)
