### ISSUE TITLE
Change "Colors"'s story "Content colors" to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2509]
In the file of:
`packages/core/src/storybook/stand-alone-documentaion/colors/content-color-row/content-color-row.jsx`
which can be seen on our [Colors story](https://vibe.monday.com/?path=/story/foundations-colors--content-colors&globals=theme:Dark) page, we do not currently use Vibe's `Text` component on some of the stories, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

```typescript
<tr className="content-color-row">
  <ContentColorCell>{`--${colorName}`}</ContentColorCell>
  <ContentColorCell style={regularStyle} />
  <ContentColorCell style={hoverStyle} />
  <ContentColorCell style={selectedStyle} />
</tr>
```
--> Something like
```typescript
<tr className="content-color-row">
  <ContentColorCell>
    <Text>{`--${colorName}`}</Text>
  </ContentColorCell>
  <ContentColorCell style={regularStyle} />
  <ContentColorCell style={hoverStyle} />
  <ContentColorCell style={selectedStyle} />
</tr>
```

Change the headers of the table as well in `packages/core/src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.jsx`.

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by noyshlomo** [comment]
Hi, Can you please assign this to me?

**Comment by YossiSaadi** [comment]
@noyshlomo go for it :)

**Comment by YossiSaadi** [comment]
Hey @noyshlomo, please update if you still planning on working on that one

**Comment by noyshlomo** [comment]
Yes, I’m on this today. Thanks!
