### ISSUE TITLE
Change "Button"'s "OnColorStates" story to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2510]
In the file of:
`packages/core/src/components/Button/__stories__/Button.stories.tsx`
which can be seen on our [Button story](https://vibe.monday.com/?path=/story/buttons-button--on-color-states&globals=theme:Dark) page, we do not currently use Vibe's `Text` component on some of the stories, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

```typescript
<span style={{ marginBottom: "var(--sb-spacing-small)" }}>Regular</span>
```
--> Something like
```typescript
<Text type={Text.types.TEXT1} style={{ marginBottom: "var(--sb-spacing-small)" }}>
  Regular
</Text>
```

Notice to fix for the "Disabled" title as well underneath it.

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by VeerChaurasia** [comment]
hi @YossiSaadi please assign this issue to me

**Comment by YossiSaadi** [comment]
@VeerChaurasia go for it :)

**Comment by YossiSaadi** [comment]
Hey @VeerChaurasia, please update if you still planning on working on that one

**Comment by VeerChaurasia** [comment]
Yaa i am working
