### ISSUE TITLE
Change "ButtonGroups"'s stories to use `Text` component

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2511]
In the file of:
`packages/core/src/components/ButtonGroup/__stories__/ButtonGroup.stories.tsx`
which can be seen on our [ButtonGroup story](http://localhost:7008/?path=/story/buttons-buttongroup--size&globals=theme:Dark) page, we do not currently use Vibe's `Text` component on some of the stories, but instead use inline string.
It also causes theme issues where a story doesn't look right on dark themes.

The problematic stories are:
- Size
- ButtonGroupInSettings

```typescript
<span style={{ marginBottom: "var(--sb-spacing-small)" }}>Regular</span>
```
--> Something like
```typescript
<Text type={Text.types.TEXT1} style={{ marginBottom: "var(--sb-spacing-small)" }}>
  Regular
</Text>
```

- Notice to fix for both "Disabled" and "Regular" titles in Size story.
- Notice also to use `TEXT1` to keep same sizing
- Notice to fix "ButtonGroupInSettings" story as well

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7080412658

**Comment by VeerChaurasia** [comment]
hey @YossiSaadi can I work on this ?

**Comment by YossiSaadi** [comment]
@VeerChaurasia go for it :)

**Comment by YossiSaadi** [comment]
Hey @VeerChaurasia, please update if you still planning on working on that one as well
