### ISSUE TITLE
Fix `withLiveEdit`'s sticky section behavior for actions

### ISSUE THREAD

**Issue by YossiSaadi** [mondaycom/vibe#2513]
In the Storybook decorator:
`packages/core/src/storybook/decorators/withLiveEdit/withLiveEdit.tsx`
we have the actions section:
```typescript
...
<section className={styles.actions}>
  <LiveEditorAction onClick={onCopyClick} disabled={isCopied}>
    {isCopied ? "Copied" : "Copy"}
  </LiveEditorAction>
  <LiveEditorAction onClick={onFormatClick}>Format</LiveEditorAction>
  <LiveEditorAction onClick={onResetClick}>Reset</LiveEditorAction>
</section>
...
```

it currently not stick properly on the right bottom side while scrolling.

`LiveEdit` can be seen for example in the [Button story](https://vibe.monday.com/?path=/docs/buttons-menubutton--docs#sizes).
![image](https://github.com/user-attachments/assets/aa0deb07-3bb4-457a-9031-009ba9f9c4ad)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/7623200949

**Comment by malavshah9** [comment]
@YossiSaadi  Would like to work on this. Assign this to me.

**Comment by YossiSaadi** [comment]
@malavshah9 go for it, good luck! :)

**Comment by YossiSaadi** [comment]
Hey @malavshah9, please update here if you're still planning working on that one 🙂

**Comment by malavshah9** [comment]
Yes I AM @YossiSaadi

**Comment by YossiSaadi** [comment]
Awesome! 🎉

**Comment by malavshah9** [comment]
@YossiSaadi  Review this once you get time: https://github.com/mondaycom/vibe/pull/2546
