### ISSUE TITLE
docs: convert VirtualizedList stories helpers file to TS

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2514]
Convert the `VirtualizedList` stories helpers file to TypeScript:

- Change the file extension to tsx
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.helpers.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/views/80492480/pulses/7623433691)

**Comment by Piyush-Tilokani** [comment]
Can you please assign this to me?
