### ISSUE TITLE
docs: convert RadioButton stories interactions file to TS 

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2517]
Convert the `RadioButton` stories interactions file to TypeScript:

- Change the file extension to ts
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/components/RadioButton/__stories__/RadioButton.stories.interactions.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/views/80492480/pulses/7623469020)

**Comment by malavshah9** [comment]
@rivka-ungar  Assign this to me. Would like to work on this.

**Comment by karthik-script** [comment]
Hi @rivka-ungar , I can fix this issue for you. Please assign it to me. Thanks.

**Comment by VeerChaurasia** [comment]
hey @rivka-ungar can I work on this one?
