### ISSUE TITLE
docs: convert dropdown-in-modals stories file to TS

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2518]
Convert the dropdown-in-modals stories file to TypeScript:

- Change the file extension to stories.tsx
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files

`packages/core/src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/views/80492480/pulses/7623480229)

**Comment by blunterdecosta123** [comment]
Hi @rivka-ungar I would like to work on this issue.

**Comment by rivka-ungar** [comment]
@blunterdecosta123 sure :)
