### ISSUE TITLE
docs: convert useActiveDescendantListFocus stories file to TS

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2519]
Convert the `useActiveDescendantListFocus` stories file to TypeScript:
- Change the file extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7623486349)

**Comment by malavshah9** [comment]
@rivka-ungar  Assign this to me. Would like to work on this.

**Comment by karthik-script** [comment]
Hi @rivka-ungar , I can fix this issue for you. Please assign it to me. Thanks.
