### ISSUE TITLE
docs: convert useGridKeyboardNavigation stories file to TS

### ISSUE THREAD

**Issue by rivka-ungar** [mondaycom/vibe#2521]
Convert the `useGridKeyboardNavigation` stories file to TypeScript:
- Change the file extension to `stories.tsx`
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files
`packages/core/src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/pulses/7623503263)

**Comment by aarifkhan7** [comment]
Hey, can you assign this issue to me?

Thanks!
