### ISSUE TITLE
support continous hover between anchor and dialog

### ISSUE THREAD

**Issue by etaylib** [mondaycom/vibe#35]
I wish to keep the gap between the anchor and the dialog, but then I can't hover into it.
We wish to have support for hovering both dialog and its anchor, keep it open, and be able to go from one to the other using the mouse without closing it.

**Comment by sanjaykumaryada** [comment]
Hi @etaylib  can you assign this to me?

**Comment by talkor** [comment]
Already possible using `showOnDialogEnter` prop :)
